export enum PageName {
	LOGIN_PAGE,
	USER_PAGE,
	ADMIN_PAGE,
	PRODUCTLIST_PAGE,
	CART_PAGE,
	USER_ADD_PAGE,
	USER_REMOVE_PAGE,
	ADMIN_ADD_PAGE,
	ADMIN_REMOVE_PAGE
}
export enum UserType {
	ADMIN='ADMIN',
	USER='USER'
}